export const blogData = [
	{
		id: 1,
		title: "Getting started with Refine, the React-based framework",
		desc: "Get started with Refine, the React-based framework for data-intensive apps with this tutorial and example build.",
		date: "January 24, 2022",
		time: "12 mins read",
		tags: "Refine, React",
		platform: "LogRocket",
		link: "https://blog.logrocket.com/getting-started-refine-react-based-framework/",
	},
	{
		id: 2,
		title: "Build responsive themes and components with Mantine",
		desc: "Learn how to build responsive themes and components with Mantine, a flexible and easy-to-use new UI library.",
		date: "April 22, 2022",
		time: "11 mins read",
		tags: "Mantine UI, React",
		platform: "LogRocket",
		link: "https://blog.logrocket.com/build-responsive-themes-components-mantine/",
	},
	{
		id: 3,
		title: "Build an animated cloud generator with SVG and CSS",
		desc: "Create realistic outdoor scenes by generating animated clouds with only SVG and CSS in this React tutorial.",
		date: "December 6, 2021",
		time: "8 mins read",
		tags: "SVG, CSS, React",
		platform: "LogRocket",
		link: "https://blog.logrocket.com/build-animated-cloud-generator-svg-css/",
	},
	{
		id: 4,
		title: "My Experience with the Open Source Challenge 2021",
		desc: "Open Source Challenge 2021",
		date: "September 6, 2021",
		time: "2 mins read",
		tags: "Personal",
		platform: "Hashnode",
		link: "https://sproff.hashnode.dev/my-experience-with-the-open-source-challenge-2021",
	},
];
