import { FaTwitterSquare } from "react-icons/fa";

export const projects = [
	{
		id: 1,
		title: "Bimal's Closet",
		tools: "React + Chakra-UI + NodeJS + ExpressJS + MongoDB",
		description: "Clothing e-commerce web app.",
		live_link: "https://bimals-closet.vercel.app/",
		github_link: "https://github.com/Sproff/bimals-closet",
		isDisabled: false,
	},
  {
		id: 2,
		title: "GitHub User Search",
		tools: "React + Chakra-UI + Redux + GitHub API",
		description: "A platform for searching github users.",
		live_link: "https://github-user-search-redux.vercel.app",
		github_link: "https://github.com/Sproff/github-user-search-redux",
		isDisabled: false,
	},
	// {
	// 	id: 3,
	// 	title: "Startar",
	// 	tools: "React + Styled-Components + NodeJS + ExpressJS + MongoDB",
	// 	description: "Tech platform for university freelancers.",
	// 	live_link: "https://startar.vercel.app",
	// 	github_link: "",
	// 	isDisabled: true,
	// },
	{
		id: 3,
		title: "Crypto App",
		tools: "Html + Css + JS + Bootstrap",
		description: "Crypto trading app. It has user & admin dashboards.",
		live_link: "https://mycryptotrade.netlify.app",
		github_link: "",
		isDisabled: FaTwitterSquare,
	},
	// {
	// 	id: 5,
	// 	title: "Studiotime Clone",
	// 	tools: "Html + Css + JS + Bootstrap",
	// 	description: "An online community to rent music studios.",
	// 	live_link: "https://studiotime.netlify.app/",
	// 	github_link: "https://github.com/Sproff/Studiotime",
	// 	isDisabled: false,
	// },
	// {
	// 	id: 6,
	// 	title: "New Movieshow",
	// 	tools: "Html + Css + JS + MovieDb Api",
	// 	description: "An app where you can see the latest movies.",
	// 	live_link: "https://newmovieshow.netlify.app",
	// 	github_link: "https://github.com/Sproff/MovieAPI",
	// 	isDisabled: false,
	// },
	{
		id: 4,
		title: "Google DSC-FUOYE",
		tools: "Html + Css + JS + Bootstrap",
		description: "Tech community",
		live_link: "https://dsc-fuoye.com",
		github_link: "",
		isDisabled: true,
	},
];
